########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library aaMI
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.0
%define packrel  0
%define rel      1
%define packname aaMI
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL version 2 or newer
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Mutual information for protein sequence alignments
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
This package contains four functions. read.FASTA reads in a
FASTA-format alignment file and parses it into a data frame. read.CX reads
in a ClustalX .aln-format file and parses it into a data frame. read.Gdoc
reads in a GeneDoc .msf-format file and parses it into a data frame. The
alignment data frame returned by each of these functions has the sequence
IDs as the row names and each site in the alignment is a column in the data
frame. The program aaMI calculates the mutual information between each pair
of sites (columns) in the protein sequence alignment data frame.

Author(s)
Kurt Wollenberg <kurt.wollenberg@gmail.com>

2005-06-21

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
