########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library accuracy
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.04
%define packrel  0
%define rel      1
%define packname accuracy
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: GPL 2.0
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Tools for testing and improving accuracy of statistical results.
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
This is a suite of tools designed to test and improve the accuracy of
statistical computation, including: Summarization of the sensitivity of linear
and non-linear models (lm, glm, mle, nls) to
measurement and numerical error; A generalized cholesky method for
correcting non-invertable Hessians; Tests for
the global optimality of non-linear regression and maximum likelihood results;
Tools for obtaining true random numbers using entropy collected from the system
and/or entropy servers on the internet;
A method for converting floating point numbers to normalized fractions;
Benchmark data for checking the accuracy of basic distribution functions.

Author(s)
Micah Altman, Jeff Gill, Michael P. McDonald



%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
