########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library aws
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.3
%define packrel  0
%define rel      1
%define packname aws
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL version 2 or newerThis library is Copyright (C) 2002 Weierstrass Institute forApplied Analysis and Stochastics.
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Adaptive Weights Smoothing
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
The library contains R-functions to perform the
adaptive weights smoothing (AWS) procedure described in
Polzehl und Spokoiny (2000), Adaptive weights smoothing with
applications to image restoration. Journal of the Royal Statistical
Society, Ser. B,  62, 2, 335--354
and its generalizations to local polynomial models as
described in Polzehl und Spokoiny (2003), Varying coefficient regression
modeling by adaptive weights smoothing, WIAS-Preprint 818
and to local likelihood models as described in Polzehl und Spokoiny (2002).
Local likelihood modelling by adaptive weights smoothing, WIAS-Preprint 787.
The functions awsuni, awsbi and awstri are superseded by functions aws and laws
and will be removed in later versions.

Author(s)
Joerg Polzehl <polzehl@wias-berlin.de>

2003-11-17

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
