########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library bayesm
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.1
%define packrel  2
%define rel      1
%define packname bayesm
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL (version 2 or later)
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Bayesian Inference for Marketing/Micro-econometrics
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
bayesm covers many important models used
in marketing and micro-econometrics applications.
The package includes:
Bayes Regression (univariate or multivariate dep var),
Multinomial Logit (MNL) and Multinomial Probit (MNP),
Multivariate Probit,
Negative Binomial Regression,
Multivariate Mixtures of Normals,
Hierarchical Linear Models with normal prior and covariates,
Hierarchical Multinomial Logits with mixture of normals prior
and covariates,
Hierarchical Negative Binomial Regression Models,
Bayesian analysis of choice-based conjoint data,
Bayesian treatment of linear instrumental variables models,
and
Analyis of Multivariate Ordinal survey data with scale
usage heterogeneity (as in Rossi et al, JASA (01)).
For further reference, consult our book, Bayesian Statistics and
Marketing by Allenby, McCulloch and Rossi.

Author(s)
Peter Rossi <peter.rossi@ChicagoGsb.edu>,
Rob McCulloch <robert.mcculloch@ChicagoGsb.edu>.

2005-07-05

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
