########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library car
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.0
%define packrel  13
%define rel      1
%define packname car
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL version 2 or newer
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Companion to Applied Regression
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:

This package accompanies J. Fox, An R and S-PLUS Companion to Applied Regression,
Sage, 2002.
The package contains mostly functions for applied regression, linear models, and
generalized linear models, with an emphasis on regression diagnostics, particularly
graphical diagnostic methods. There are also some utility functions.
With some exceptions, I have tried not to duplicate capabilities in the basic distribution of R,
nor in widely used packages. Some of the functions in car will use functions
in the MASS package, if it is present; the subsets function graphs
objects produced by the regsubsets function in the leaps package. Where relevant, the functions in
car are consistent with na.action = na.omit or na.exclude.

Author(s)
John Fox <jfox@mcmaster.ca>. I am grateful to Douglas Bates, David Firth, Michael Friendly,
Georges Monette, Brian Ripley, and Sanford Weisberg for various suggestions.

2004/7/13

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
