########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library changeLOS
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.1.7
%define packrel  0
%define rel      1
%define packname changeLOS
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: GPL (version 2 or later)
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Change in LOS
BuildRequires: R-base
PreReq: R-base
Requires: 
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
Change in length of hospital stay (LOS) is frequently used to assess the impact and the costs of hospital-acquired complications. In order to compute the attributable change in LOS, it is crucial to account for the timing of events: A complication can only have an effect on LOS, once it has occured. These temporal dynamics can be adequately handled by multistate models; however, there is few software for such models available. We introduce an R-package "changeLOS" for computing change in LOS based on methods described in Schulgen and Schumacher (1996). We will illustrate the program on data from a prospective cohort study on hospital-acquired infections. Main features of the R-package "changeLOS" are R-methods to: (1) describe the multi-state model. (2) compute the Aalen-Johansen estimator for the matrix of transition probabilities P(u-, u) for all observed transition times u.(3) compute the Aalen-Johansen estimator for the matrix of transition probabilities P(s,t); the estimator is a finite matrix product of matrices P(u-,u) for every observed event time in the interval(s,t]. (4) visualize the temporal dynamics of the data, illustrated by transition probabilities. (5) compute and visualize change in LOS. (6) compute bootstrap variances for change in LOS.

Author(s)
Matthias Wangler <mw@imbi.uni-freiburg.de>, Jan Beyersmann <jan@fdm.uni-freiburg.de>

2005-07-13

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
