########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library CoCo
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      0.1.6.3
%define packrel  0
%define rel      1
%define packname CoCo
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: Copyright (C) by Jens Henrik Badsberg, non-profit use and redistribution permitted (see COPYING for details)
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Graphical modelling by CoCo
BuildRequires: R-base
PreReq: R-base
Requires:  R-dynamicGraph
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package bundle:
Interface to CoCo from R

Author(s)
Jens Henrik Badsberg <JensHenrik.Badsberg@agrsci.dk>

2004/08/24

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/CoCoGraph/src && (cd %{packname}/CoCoGraph/src; rm -f *.o *.so)
test -d %{packname}/CoCoObjects/src && (cd %{packname}/CoCoObjects/src; rm -f *.o *.so)
test -d %{packname}/CoCoCore/src && (cd %{packname}/CoCoCore/src; rm -f *.o *.so)
test -d %{packname}/CoCoOldData/src && (cd %{packname}/CoCoOldData/src; rm -f *.o *.so)
test -d %{packname}/CoCoRaw/src && (cd %{packname}/CoCoRaw/src; rm -f *.o *.so)
test -d %{packname}/CoCo/src && (cd %{packname}/CoCo/src; rm -f *.o *.so)
test -d %{packname}/CoCoCg/src && (cd %{packname}/CoCoCg/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/CoCoGraph
%{prefix}/lib/R/library/CoCoObjects
%{prefix}/lib/R/library/CoCoCore
%{prefix}/lib/R/library/CoCoOldData
%{prefix}/lib/R/library/CoCoRaw
%{prefix}/lib/R/library/CoCo
%{prefix}/lib/R/library/CoCoCg


####### end of spec-file ################################################
