########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library conf.design
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      0.0
%define packrel  4
%define rel      1
%define packname conf.design
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: This software may be re-distributed freely and used forany non-commercial purpose.
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Construction of factorial designs
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
This small library contains a series of simple tools for
constructing and manipulating confounded and fractional
factorial designs. To some extent these complement those
already available in S-PLUS 3.1 and 3.2, (but they
may well be rendered obsolete by S+DOX, to which the author
does not yet have access).

Author(s)
Bill Venables <Bill.Venables@CMIS.CSIRO.AU>

2005-04-08

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
