########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library corpcor
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.0.0
%define packrel  0
%define rel      1
%define packname corpcor
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: GPL version 2 or newer
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Efficient Estimation of Covariance and (Partial) Correlation
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
This package implements a shrinkage estimator to allow
the efficient inference of large-scale covariance matrices
from small sample data.  The resulting estimates are always
positive definite, more accurate than the empirical estimate,
well conditioned, computationally inexpensive, and require
only little a priori modeling.  The package also contains
similar functions for inferring correlations and partial
correlations.  In addition, it provides functions for fast svd
computation, for computing the pseuoinverse, and
for checking the rank and positive definiteness of a matrix.

Author(s)
Juliane Schaefer <schaefer@stat.uni-muenchen.de> and
Korbinian Strimmer <korbinian.strimmer@lmu.de>.

2005-08-10

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
