########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library corpcor
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.4.5
%define packrel  0
%define rel      1
%define packname corpcor
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: GPL version 2 or newer
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Efficient Estimation of Covariance and (Partial) Correlation
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
This package implements an analytic shrinkage approach
for inferring the covariance matrix.  The estimator is statistically
highly accurate and efficient, applicable to "small n, large p" data,
and always returns a positive definite and well-conditioned matrix.
Nevertheless, this method requires only little a priori modeling and is
computationally cheap. In addition to covariance estimation the
package contains similar functions for inferring variances, correlations,
partial correlations, partial variances, and regression coefficients.
Furthermore, it provides  functions for fast SVD computation, for computing
the pseudoinverse, for checking the rank and positive definiteness of a
matrix, and for the computationally fast inversion of the covariance
and correlation matrix.

Author(s)
Juliane Schaefer, Rainer Opgen-Rhein, and Korbinian Strimmer.

2006-09-17

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --html
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --html
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
