########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library coin
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      0.3
%define packrel  3
%define rel      1
%define packname coin
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Conditional Inference Procedures in a Permutation Test Framework
BuildRequires: R-base
PreReq: R-base
Requires:  R-norm R-mvtnorm R-modeltools
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
Conditional inference procedures for the general independence
problem including two-sample, K-sample, correlation, censored, ordered and
multivariate problems.

Author(s)
Torsten Hothorn and Kurt Hornik, with contributions by
Mark van de Wiel and Achim Zeileis

$Date: 2005/09/06 15:51:37 $

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
