########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library cyclones
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.1
%define packrel  5
%define rel      1
%define packname cyclones
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL version 2 or newer. The use should be acknowledged in publication acknowledgement: .. "results were obtained using cyclones by Benestad (The Norwegian Meteorological Institute and the Norwegian Research Council's RegClim programme)."
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Cyclone identification
BuildRequires: R-base
PreReq: R-base
Requires:  R-akima R-ncdf R-clim.pact
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
Functions for locating local minima/maxima

Author(s)
Rasmus E. Benestad <rasmus.benestad@met.no>

August 11 2005

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
