########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library digest
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      0.2.0
%define packrel  0
%define rel      1
%define packname digest
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: GPL Version 2
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Create cryptographic hash digests of R objects
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
The digest package provides functions for the creation of
`hash' digests of arbitrary R objects using the md5, sha-1 and
crc32 algorithms permitting easy comparison of R language objects.
The md5 algorithm by Ron Rivest is specified in RFC 1321, the SHA-1
algorithm is specified in FIPS-180-1 and the crc32 algorithm is
described in ftp://ftp.rocksoft.com/cliens/rocksoft/papers/crc_v3.txt.
For md5 and sha-1, this packages uses two small standalone C
implementations that were provided by by Christophe Devine. For
crc32, code from the zlib library is used.
.
Please note that this package is not meant to be used for
cryptographic purposes for which more comprehensive (and widely
tested) libraries such as OpenSSL should be used.

Author(s)
Dirk Eddelbuettel <edd@debian.org>

$Date: 2005/04/07 02:09:19 $

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
