########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library drfit
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      0.03
%define packrel  5
%define rel      1
%define packname drfit
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL version 2 or newer
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Dose-response data evaluation
BuildRequires: R-base
PreReq: R-base
Requires:  R-RODBC
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
drfit provides basic functions for accessing the
dose-response data of the UFT Bremen, Department of Bioorganic Chemistry,
fitting dose-response curves to this and similar data, calculating some
(eco)toxicological parameters and plotting the results. Functions that are
fitted are the cumulative densitiy function of the lognormal distribution,
of the logistic distribution and a linear-logistic model, derived from the
latter, which is used to describe data showing stimulation at low doses
(hormesis). The author would be delighted if anyone would join in this
effort of creating useful and useable tools for dealing with dose-response
data from biological testing.

Author(s)
Johannes Ranke <jranke@uni-bremen.de>

2004-09-08

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
