########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library dse
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      2004.4
%define packrel  1
%define rel      1
%define packname dse
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: Free. See the LICENCE file for details.
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - 
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package bundle:
Multivariate Time Series Library
For each package there is a Users' Guide is available
in doc/*-guide.pdf and also at http://www.bank-banque-canada.ca/pgilbert
The package dse1 is the base system, including multivariate
ARMA and State Space models.
Package dse2 has extensions for evaluating estimation
techniques, forecasting, and for evaluating forecasting models.
Package tframe is a kernel of methods for programming with time series.
These packages require the package setRNG.
See also the related bundle dseplus.

Author(s)
Paul Gilbert <pgilbert@bank-banque-canada.ca>



%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/tframe/src && (cd %{packname}/tframe/src; rm -f *.o *.so)
test -d %{packname}/dse1/src && (cd %{packname}/dse1/src; rm -f *.o *.so)
test -d %{packname}/dse2/src && (cd %{packname}/dse2/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/tframe
%{prefix}/lib/R/library/dse1
%{prefix}/lib/R/library/dse2


####### end of spec-file ################################################
