########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library ebayesthresh
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.02
%define packrel  0
%define rel      1
%define packname ebayesthresh
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: GPL version 2 or newer
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Empirical Bayes thresholding and related methods
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
Carries out Empirical Bayes thresholding using the methods
developed by Johnstone and Silverman.  The basic problem is to estimate a mean
vector given a vector of observations of the mean vector plus white noise, taking
advantage of possible sparsity in the mean vector.  Within a Bayesian formulation, the
elements of the mean vector are modelled as having, independently, a distribution that
is a mixture of an atom of probability at zero and a suitable hevay-tailed distribution.
The mixing parameter can be estimated by a marginal maximum likelihood approach.
This leads to an adaptive thresholding approach on the original data.  Extensions of
the basic method, in particular to wavelet thresholding, are also implemented
within the package.

Author(s)
Bernard Silverman (with major intellectual input from Iain
Johnstone)

2004-09-04

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
