########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library ellipse
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      0.2
%define packrel  14
%define rel      1
%define packname ellipse
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: This library was written by D. J. Murdoch andE. D. Chow. This software is licensed under the GPL terms. Itis free software and comes with ABSOLUTELY NO WARRANTY.
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Functions for drawing ellipses and ellipse-like confidence regions
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
This package contains various routines for drawing
ellipses and ellipse-like confidence regions, implementing the plots
described in Murdoch and Chow (1996), A graphical display of large
correlation matrices, The American Statistician 50, 178-180. There are
also routines implementing the profile plots described in Bates and
Watts (1988), Nonlinear Regression Analysis and its Applications.

Author(s)
Duncan Murdoch <murdoch@stats.uwo.ca> and E. D. Chow
(porting to R by Jesus M. Frias Celayeta <iosu@bureau.ucc.ie>)

2004-08-06

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
