########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library extRemes
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.12
%define packrel  0
%define rel      1
%define packname extRemes
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: GPL Version 2 or later.
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Extreme value toolkit.
BuildRequires: R-base
PreReq: R-base
Requires:  R-ismev R-sm
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
Uses Stuart Coles' (Coles, Stewart, "An introduction to
statistical modeling of extreme values", Springer-Verlag, London 2001)
S-plus functions as ported to the R programming language (ismev) by Alec
Stephenson (http://www.maths.lancs.ac.uk/~stephena/).  This toolkit provides
a Graphical User Interface (GUI) to ismev for pedagogical purposes.

Author(s)
Eric Gilleland, Rick Katz, Greg Young

March 15 2004

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
