########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library far
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      0.6
%define packrel  0
%define rel      1
%define packname far
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: LGPL version 2.1 <http://www.gnu.org/copyleft/lesser.html>
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Modelization for Functional AutoRegressive processes
BuildRequires: R-base
PreReq: R-base
Requires: 
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
Modelizations and previsions functions for
Functional AutoRegressive processes using
nonparametric methods: functional kernel,
estimation of the covariance operator in
a subspace, ...

Author(s)
Damon Julien <julien.damon@free.fr>
Guillas Serge <guillas@uchicago.edu>

2005-01-12

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
