########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library fpc
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.1
%define packrel  2
%define rel      1
%define packname fpc
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Fixed point clusters, clusterwise regression and discriminant plots
BuildRequires: R-base
PreReq: R-base
Requires: 
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
Fuzzy and crisp fixed point cluster analysis
based on Mahalanobis distance and linear regression fixed point
clusters. Semi-explorative, semi-model-based clustering methods,
operating on n*p data, do not need prespecification of number of
clusters, produce overlapping clusters. Symmetric and asymmetric
discriminant projections separate
groups optimally, used to visualize the separation of
groupings. Corresponding plot methods. Clusterwise linear
regression by normal mixture modeling. Cluster validation statistics
for distance based clustering. Note: If you use an R-version older
than 1.9.0, you will need packages lqs and mva installed.

Author(s)
Christian Hennig <hennig@math.uni-hamburg.de>

2004-04-23

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
