########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library frailtypack
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      2.0
%define packrel  0
%define rel      1
%define packname frailtypack
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL version 2 or newer
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Frailty models using maximum penalized likelihood estimation
BuildRequires: R-base
PreReq: R-base
Requires: 
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
Fit a shared gamma frailty model and Cox proportional hazards model using a Penalized Likelihood
on the hazard function. Left truncated, censored data and strata (max=2) are allowed. Clustered and
recurrent survival times can be studied  (the  Andersen-Gill (1982) approach has been implemented
for recurrent events). An automatic choice of the smoothing parameter is possible using an approximated
cross-validation procedure.

Author(s)
Modified Fortran routines, R code and packaged by Juan R Gonzalez <jrgonzalez@ico.scs.es>.
Original Fortran routines by Virginie Rondeau <Virginie.Rondeau@isped.u-bordeaux2.fr>

2005-05-17

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
