########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library gap
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      0.8
%define packrel  2
%define rel      1
%define packname gap
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: Programs included in this package by Jing hua Zhao will beunder GPL. Specific requirement may be possible for programswritten by other authors.
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Genetic analysis package
BuildRequires: R-base
PreReq: R-base
Requires:  R-haplo.score
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
This is an integrated package for genetic data analysis
of both population and family data. Currently it contains
functions for sample size calculations of both population-based
and family-based designs, probability of familial disease
aggregation, kinship calculation, some statistics in linkage
analysis, and association analysis involving one or more
genetic markers including haplotype analysis. In the future
it will incorporate programs for path and segregation analyses,
as well as other statistics in linkage and association analyses.

Author(s)
Jing hua Zhao in collaboration with other colleagues, and with
help from Kurt Hornik and Brian Ripley of the R core development team

2004-8-16

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
