########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library gap
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.0
%define packrel  3
%define rel      1
%define packname gap
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: Programs included in this package by Jing hua Zhao will beunder GPL. Specific requirement may be possible for programswritten by other authors.
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - 
BuildRequires: R-base
PreReq: R-base
Requires:  R-genetics
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package bundle:
This is an experimental package bundle based on the
original R package for genetic data analysis (gap), it currently
consists of gap, pathmix and pointer.

Author(s)
Jing hua Zhao in collaboration with other colleagues, and with
help from Kurt Hornik and Brian Ripley of the R core development team

2005-7-24

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/gap/src && (cd %{packname}/gap/src; rm -f *.o *.so)
test -d %{packname}/pathmix/src && (cd %{packname}/pathmix/src; rm -f *.o *.so)
test -d %{packname}/pointer/src && (cd %{packname}/pointer/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/gap
%{prefix}/lib/R/library/pathmix
%{prefix}/lib/R/library/pointer


####### end of spec-file ################################################
