########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library GeneTS
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      2.7
%define packrel  0
%define rel      1
%define packname GeneTS
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: GPL version 2 or newer
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Microarray Time Series and Network Analysis
BuildRequires: R-base
PreReq: R-base
Requires:  R-dr R-locfdr R-corpcor
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
GeneTS is a package for analyzing gene expression
(time series) data. Currently, two kinds of analyzes are supported:
the idenfication of periodic genes, and the inference of
large-scale gene association networks.  In order to recover
networks GeneTS implements a strategy for fast model selection
of graphical Gaussian models (GGMs) via local fdr multiple testing.
In addition, GeneTS offers general data structures and functions for
longitudinal data with multiple variables, repeated measurements,
and irregularly spaced time points. For plotting the gene networks
GeneTS uses the "graph" and "Rgraphviz" packages, available from
http://www.bioconductor.org.

Author(s)
Miika Ahdesmaki <miika.ahdesmaki@tut.fi>,
Konstantinos Fokianos <fokianos@ucy.ac.cy>,
Juliane Schaefer <schaefer@stat.uni-muenchen.de>, and
Korbinian Strimmer <korbinian.strimmer@lmu.de>.

2005-08-15

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
