########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library GeneNT
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.3
%define packrel  0
%define rel      1
%define packname GeneNT
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: GPL version 2 or newer
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Relevance or Dependency network and signaling pathway discovery
BuildRequires: R-base
PreReq: R-base
Requires:  R-e1071 R-GeneTS
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
The package implements a two-stage algorithm to screen co-expressed
gene pairs with controlled False Discovery Rate (FDR) and Minimum Acceptable Strength
(MAS). The packages also constructs relevance networks and clusters co-expressed
genes (both similarly co-expressed and transitively co-expressed). In addtion, it
includes new correlation estimators and non-parametric statistical inference procedure
for replicated gene microarray data.

Author(s)
Dongxiao Zhu (http://www-personal.umich.edu/~zhud/genent.htm)



%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --html
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --html
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
