########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library gregmisc
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      2.0.8
%define packrel  0
%define rel      1
%define packname gregmisc
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: GPL (version 2 or later)
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Backword compatibility package for gregmisc bundle
BuildRequires: R-base
PreReq: R-base
Requires:  R-gplots R-gtools R-gmodels R-gdata
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
Backword compatibility package for gregmisc bundle.  This package
simply loads the other packages within the gregmisc bundle, in
in order to simulate the old behavior when gregmisc was a single
package.

Author(s)
Gregory R. Warnes.  Includes R source code and documentation
contributed by
- Ben Bolker,
- Lodewijk Bonebakker,
- Bendix Carstensen,
- R. Gentleman,
- Kjetil Halvorsen,
- W. Huber
- Nitin Jain,
- Andy Liaw,
- Don MacQueen,
- M. Maechler,
- Arni Magnusson,
- Jim Rogers,
- Marc Schwartz,
- William Venables,
- Ian Wilson,
and others (let me know if I missed you!), as well as the Perl
modules
- "IO-stringy" (copyright 1996 by Eryq, and 1999,2001 by
ZeeGee Software Inc),
- OLE::Storage_Lite (copyright 2000,2001 by Kawai Takanori),
- Spreadsheet::ParseExcel (copyright 2000-2002 by Kawai
Takanori )
under the terms of the GNU General Public Licence (GPL).



%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
