########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library HighProbability
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.0
%define packrel  2
%define rel      1
%define packname HighProbability
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: Mozilla Public License 1.1 (http://www.mozilla.org/MPL/)
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - HighProbability estimates which alternative hypotheses have frequentist or Bayesian probabilities at least as great as a specified threshold, given a list of p-values.
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
HighProbability provides a simple, fast, reliable solution to the multiple testing problem. Given a vector of p-values or achieved significance levels computed using standard frequentist inference, HighProbability determines which ones are low enough that their alternative hypotheses can be considered highly probable. The p-value vector may be determined using existing R functions such as t.test, wilcox.test, cor.test, or sample. HighProbability can be used to detect differential gene expression and to solve other problems involving a large number of hypothesis tests.

Author(s)
David R. Bickel



%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
