########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library hoa
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.0
%define packrel  0
%define rel      1
%define packname hoa
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL (version 2 or later)
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - 
BuildRequires: R-base
PreReq: R-base
Requires:  R-statmod
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package bundle:
Various functions for higher order likelihood-based
inference

Author(s)


2005-05-31

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/cond/src && (cd %{packname}/cond/src; rm -f *.o *.so)
test -d %{packname}/marg/src && (cd %{packname}/marg/src; rm -f *.o *.so)
test -d %{packname}/nlreg/src && (cd %{packname}/nlreg/src; rm -f *.o *.so)
test -d %{packname}/csampling/src && (cd %{packname}/csampling/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/cond
%{prefix}/lib/R/library/marg
%{prefix}/lib/R/library/nlreg
%{prefix}/lib/R/library/csampling


####### end of spec-file ################################################
