########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library HTMLapplets
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      0.1
%define packrel  2
%define rel      1
%define packname HTMLapplets
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL version 2 or newer. Copyright statement for ptolemy: http://ptolemy.eecs.berkeley.edu/copyright.htm
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Dynamic visualisation in HTML documents
BuildRequires: R-base
PreReq: R-base
Requires:  R-R2HTML
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
Functions inserting dynamic scatterplots and grids in documents generated by R2HTML. To view the applets you must install a Java plugin (http://java.sun.com/products/plugin/). The plot applet is a modified version of PtPlot 5.3 (http://ptolemy.eecs.berkeley.edu/).

Author(s)
Gregoire Thomas <Gregoire.Thomas@ugent.be>

2004-12-05

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
