########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library kappalab
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      0.1
%define packrel  3
%define rel      1
%define packname kappalab
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: CeCILL 2 (GNU GPL 2 compatible)
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Non-additive measure and integral manipulation functions
BuildRequires: R-base
PreReq: R-base
Requires:  R-quadprog R-kernlab
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
Kappalab, which stands for "laboratory for capacities", is an S4 tool box for capacity (or non-additive measure, fuzzy measure) and integral manipulation on a finite setting. It contains routines for handling various types of set functions such as games or capacities. It can be used to compute several non-additive integrals: the Choquet integral, the Sugeno integral, and the symmetric and asymmetric Choquet integrals. An analysis of capacities in terms of decision behavior can be performed through the computation of various indices such as the Shapley value, the interaction index, the orness degree, etc. The well-known Möbius transform, as well as other equivalent representations of set functions can also be computed. Kappalab further contains four capacity identification routines: two least squares based approaches, a maximum entropy like method based on variance minimization and an unsupervised approach grounded on parametric entropies. The functions contained in Kappalab can for instance be used for multicriteria decision making or in the framework of cooperative game theory.

Author(s)
Michel Grabisch, Ivan Kojadinovic, Patrick Meyer.

2005-05-07

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
