########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library KernSmooth
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      2.22
%define packrel  19
%define rel      1
%define packname KernSmooth
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: Unlimited use and distribution (see LICENCE).
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Functions for kernel smoothing for Wand & Jones (1995)
BuildRequires: R-base
PreReq: R-base
Requires:  R-st
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
functions for kernel smoothing (and density estimation)
corresponding to the book:
Wand, M.P. and Jones, M.C. (1995) "Kernel Smoothing".

Author(s)
S original by Matt Wand.
R port by  Brian Ripley <ripley@stats.ox.ac.uk>.

2006-09-05

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --html
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --html
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
