########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library kinship
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.1.0
%define packrel  3
%define rel      1
%define packname kinship
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: Copyright 2003 Mayo Foundation for Medical Education andResearch This program is free software; you can redistributeit and/or modify it under the terms of the GNU General PublicLicense as published by the Free Software Foundation; eitherversion 2 of the License, or (at your option) any laterversion. This program is distributed in the hope that it willbe useful, but WITHOUT ANY WARRANTY; without even the impliedwarranty of MERCHANTABILITY or FITNESS FOR A PARTICULARPURPOSE. See the GNU General Public License for more details.For other licensing arrangements, please contact TerryTherneau, Ph.D. Division of Biostatistics Mayo Clinic200 First St., SW Rochester, MN 55905 email: therneau@mayo.edu
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - mixed-effects Cox models, sparse matrices, and modeling data from large pedigrees
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
coxme: general mixed-effects Cox models; kinship: routines
to create and manipulate n by n matrices that describe the
genetic relationships between n persons; pedigree: create and
plot pedigrees; bdsmatrix: a class of objects for sparse
block-diagonal matrices (which is how kinship matrices are
stored); gchol: generalized cholesky decompositions

Author(s)
Beth Atkinson (atkinson@mayo.edu) for pedigree
functions. Terry Therneau (therneau@mayo.edu) for all other functions.

2004-9-6

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
