########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library labdsv
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.0
%define packrel  1
%define rel      1
%define packname labdsv
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL version 2 or newer
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Laboratory for Dynamic Synthetic Vegephenomenology
BuildRequires: R-base
PreReq: R-base
Requires:  R-akima
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
A variety of ordination and vegetation analyses
useful in analysis of datasets in community ecology.  Includes
many of the common ordination methods, with graphical
routines to facilitate their interpretation, as well as
several novel analyses.

Author(s)
David W. Roberts <droberts@montana.edu>

2005-01-17

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
