########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library lpSolve
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.1.9
%define packrel  0
%define rel      1
%define packname lpSolve
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: LGPL version 2
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Interface to Lp_solve v. 5 to solve linear/integer programs
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
Lp_solve is freely available (under LGPL 2) software for
solving linear, integer and mixed integer programs. In this implementation
we supply a "wrapper" function in C and some R functions that solve
general linear/integer problems, assignment problems, and transportation
problems. This version calls lp_solve version 5.

Author(s)
Michel Berkelaar and others

2005-04-14

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
