########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library magic
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.3
%define packrel  15
%define rel      1
%define packname magic
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - create and investigate magic squares
BuildRequires: R-base
PreReq: R-base
Requires:  R-abind
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
a collection of efficient, vectorized algorithms for the
creation and investigation of magic squares, including methods for
creating normal magic squares of any order greater than 2.  The
ultimate intention is for the package to be a computerized embodiment
all magic square knowledge, including direct numerical verification
of properties of magic squares (such as recent results on the
determinant of odd-ordered semimagic squares).  The package also
serves as a rebuttal to the often-heard comment "I thought R
was just for statistics".

Author(s)
Robin K. S. Hankin



%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
