########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library MCMCpack
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      0.5
%define packrel  2
%define rel      1
%define packname MCMCpack
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL version 2 or newer
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Markov chain Monte Carlo (MCMC) Package
BuildRequires: R-base
PreReq: R-base
Requires:  R-coda
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
This package contains functions for posterior
simulation for a number of statistical models. All simulation
is done in compiled C++ written in the Scythe Statistical
Library Version 1.0. All models return coda mcmc objects that
can then be summarized using the coda package.  MCMCpack
also contains some useful utility functions, including some
additional density functions and pseudo-random number generators
for statistical distributions, a general purpose Metropolis
sampling algorithm, and tools for visualization.

Author(s)
Andrew D. Martin <admartin@wustl.edu>, and
Kevin M. Quinn <kevin_quinn@harvard.edu>

2004-8-17

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
