########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library meanscore
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.0
%define packrel  6
%define rel      1
%define packname meanscore
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: free for non-commercial purposes
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Meanscore method for missing covariate data in logistic regression models
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
The Mean Score method for missing and auxiliary covariate data
is described in the paper by Reilly & Pepe in Biometrika 1995.
This likelihood-based method allows an analysis using all available
cases and hence will give more efficient estimates.
The method is applicable to cohort or case-control designs.

Author(s)
Marie Reilly PhD <marie.reilly@meb.ki.se> and Agus Salim <a.salim@cgiar.org>

2003/12/31

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
