########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library MNP
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.2
%define packrel  1
%define rel      1
%define packname MNP
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL (version 2 or later)
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - MNP: R Package for Fitting the Multinomial Probit Models
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
MNP is a publicly available R package that fits the
Bayesian Multinomial Probit models via Markov chain Monte Carlo. Along
with the standard Multinomial Probit model, it can also fit models
with different choice sets for each observation and complete or
partial ordering of all the available alternatives. The estimation
is based on the efficient marginal data augmentation algorithm that
is developed by Imai and van Dyk (2004).

Author(s)
Kosuke Imai <kimai@princeton.edu>,
Jordan Vance<jvance@princeton.edu>,
David A. van Dyk <dvd@uci.edu>.

2004-09-26

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
