########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library ncdf
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.4
%define packrel  0
%define rel      1
%define packname ncdf
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: GPL version 2 or newer
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Interface to Unidata netCDF data files
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
This package provides a high-level R interface to Unidata's
netCDF data files, which are portable across platforms and include
metadata information in addition to the data sets.
Using this package netCDF files can be opened and data sets read in easily.
It is also easy to create new netCDF dimensions, variables, and files,
or manipulate existing netCDF files.
This interface provides considerably more functionality than the "netCDF"
package.  It is not compatible with the "netCDF" package.
Release 1.2 adds better support for character variables, and miscellaneous
bug fixes.  Release 1.3 is for miscellaneous bug fixes, and improves the
documentation.  Release 1.4 improves the efficiency, and adds small bug
fixes.

Author(s)
David Pierce



%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
