########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library ncvar
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.0
%define packrel  3
%define rel      1
%define packname ncvar
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL version 2 or newer
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - High-level R Interface to NetCDF Datasets
BuildRequires: R-base
PreReq: R-base
Requires:  R-RNetCDF
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
This package provides a high-level R interface to Unidata's NetCDF
data files. Using this package netCDF datasets, and all their
associated metadata, can be read and written in one go. It is also
easy to create datasets including lots of metadata.
This package supports both the CF and default NetCDF metadata conventions.
This package
supports more general NetCDF files and conventions than the ncdf
package by David Pierce. It requires the low-level NetCDF package
RNetCDF by Pavel Michna.

Author(s)
Juerg Schmidli

2004-10-08

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --html
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --html
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
