########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library norm
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.0
%define packrel  9
%define rel      1
%define packname norm
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: The software may be distributed free of charge andused by anyone if credit is given. It has been testedfairly well, but it comes with no guarantees and theauthors assume no liability for its use or misuse.
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Analysis of multivariate normal datasets with missing values
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
Analysis of multivariate normal datasets with missing values

Author(s)
Ported to R by Alvaro A. Novo <alvaro@novo-online.net>.
Original by Joseph L. Schafer <jls@stat.psu.edu>.

2002/05/06

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
