########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library PBSmapping
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      2.01
%define packrel  0
%define rel      1
%define packname PBSmapping
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: GPL version 2 or newer
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - PBS Mapping 2
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
This software has evolved from fisheries research
conducted at the Pacific Biological Station (PBS) in Nanaimo,
British Columbia, Canada. It extends the R language to include
two-dimensional plotting features similar to those commonly
available in a Geographic Information System (GIS).  Embedded C code
speeds algorithms from computational geometry, such as finding
polygons that contain specified point events or converting between
longitude-latitude and Universal Transverse Mercator (UTM)
coordinates.  It includes data for a global shoreline and other data
sets in the public domain.

Author(s)
Nicholas Boers <BoersN@pac.dfo-mpo.gc.ca>,
Jon Schnute <SchnuteJ@pac.dfo-mpo.gc.ca>,
Rowan Haigh <HaighR@pac.dfo-mpo.gc.ca>, and others.

2004-09-22

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
