########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library powerpkg
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.2
%define packrel  0
%define rel      1
%define packname powerpkg
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: GPL version 2 or newer.
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Power analyses for the affected sib pair and the TDT design
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
(1) To estimate the power of testing for linkage using an
affected sib pair design, as a function of the recurrence risk ratios. We
will use analytical power formulae as implemented in R. These are based
on a Mathematica notebook created by Martin Farrall. (2) To examine how
the power of the transmission disequilibrium test (TDT) depends on the
disease allele frequency, the marker allele frequency, the strength of
the linkage disequilibrium, and the magnitude of the genetic effect. We
will use an R program that implements the power formulae of Abel and
Muller-Myhsok (1998). These formulae allow one to quickly compute power
of the TDT approach under a variety of different conditions. This R
program was modeled on Martin Farrall's Mathematica notebook.

Author(s)
Daniel E. Weeks

2005-07-30

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --html
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --html
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
