########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library prabclus
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.0
%define packrel  2
%define rel      1
%define packname prabclus
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Test for clustering of presence-absence data
BuildRequires: R-base
PreReq: R-base
Requires:  R-mclust
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
Distance based parametric bootstrap tests for clustering,
mainly thought for presence-absence data (clustering of species
distribution maps). Jaccard and Kulczynski distance measures, clustering
of MDS scores, and nearest neighbor based noise detection (R port of Byers
and Raftery's (1998) "NNclean"). Main functions are prabtest (for
testing), prabclust (for clustering), prabinit (for preparing the data)
and NNclean (for noise detection). The help-pages for prabtest and
prabclust contain simple standard executions.

Author(s)
Christian Hennig <hennig@math.uni-hamburg.de>

2003-07-02

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
