########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library PTAk
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.1
%define packrel  10
%define rel      1
%define packname PTAk
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: free for non-commercial purposes.
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Principal Tensor Analysis on k modes
BuildRequires: R-base
PreReq: R-base
Requires:  R-tensor
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
A multiway method to decompose a tensor (array) of any order,
as a generalisation of SVD also supporting non-identity metrics and penalisations.
2-way SVD with these extensions is also available. The package includes also some other multiway
methods: PCAn (Tucker-n) and PARAFAC/CANDECOMP with these extensions.

Author(s)
Didier Leibovici <didier.leibovici@teledetection.fr>

2004/06/14

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
