########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library qvalue
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.1
%define packrel  0
%define rel      1
%define packname qvalue
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: LGPL
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Q-value estimation for false discovery rate control
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
This package takes a list of p-values resulting from the
simultaneous testing of many hypotheses and estimates their
q-values. The q-value of a test measures the proportion of
false positives incurred (called the false discovery rate)
when that particular test is called significant. Various plots
are automatically generated, allowing one to make sensible
significance cut-offs. Several mathematical results have recently
been shown on the conservative accuracy of the estimated
q-values from this software. The software can be applied
to problems in genomics, brain imaging, astrophysics, and
data mining.

Author(s)
Alan Dabney <adabney@u.washington.edu> and
John D. Storey <jstorey@u.washington.edu>, with assistance from
Gregory R. Warnes <gregory_r_warnes@groton.pfizer.com>



%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
