########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library RCurl
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      0.3
%define packrel  0
%define rel      1
%define packname RCurl
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: BSD
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - HTTP request interface
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
The package allows one to compose HTTP requests  to fetch URIs, post forms,
etc. and process the results returned by the Web server.
This provides a great deal of control over the HTTP connection and the form
of the request while providing a higher-level interface than is available just
using R socket connections.  Additionally, the underlying implementation is robust
and extensive, supporting SSL/HTTPS, cookies, redirects, authentication, etc.

Author(s)
Duncan Temple Lang

2004-08-04

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
