########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library relax
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.00
%define packrel  0
%define rel      1
%define packname relax
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: This package was written by Hans Peter Wolf.This software is licensed under the GPL (version 2 or newer) terms.It is free software and comes with ABSOLUTELY NO WARRANTY.
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - relax -- R Editor for Literate Analysis and lateX
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
package relax contains some functions for report
writing, presentation, and programming: relax(), tangleR(),
weaveR(), slider(). "relax" is written in R and Tcl/Tk.
relax creates a new window (top level Tcl/Tk widget) that consists
of two text fields and some buttons and menus.
Text (chunks) and code (chunks) are inserted in the upper text field (report field).
Code chunks are evaluated by clicking on EvalRCode.
Results are shown in the lower text field (output field) and
will be transfered to the report field by pressing on Insert.
In this way you get correct reports. These reports can be
loaded again in cause of presentation, modification and result checking.
tangleR() and weaveR() implement a plain kind of tangling
and weaving. slider() is designed to define sliders for interactive
experiments in a simple way.
The windows version uses some ingredients of the noweb system of Norman Ramsey
(http://www.eecs.harvard.edu/~nr/noweb/intro.html),
of the Img package of Jan Nijtmans (http://www.xs4all.nl/~nijtmans/img.html),
-- notice the copyright declarations of these products.

Author(s)
Hans Peter Wolf <pwolf@wiwi.uni-bielefeld.de>

2005-06-24

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
