########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library rgdal
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      0.2
%define packrel  7
%define rel      1
%define packname rgdal
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL (version 2 or higher; see LICENSE)
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Bindings for the Geospatial Data Abstraction Library
BuildRequires: R-base
PreReq: R-base
Requires:  R-pixmap R-abind
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
Provides bindings to Frank Warmerdam's Geospatial Data Abstraction Library (GDAL) (>= 1.1.8) - this version with new-style classes. The GDAL library is external to the package, and must be correctly installed first.

Author(s)
Timothy H. Keitt <tkeitt@mail.utexas.edu> and Roger Bivand <Roger.Bivand@nhh.no>

2004-08-06

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
