########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library rimage
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      0.5
%define packrel  7
%define rel      1
%define packname rimage
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: BSD
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Image Processing Module for R
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
This package provides functions for image processing,
including sobel filter, rank filters, fft, histogram equalization, and
reading JPEG file. This package requires fftw-2 <http://www.fftw.org/>
and libjpeg <http://www.ijg.org>. This version doesn't require
pixmap package, which the older version of rimage (private only) required.
This package can be used on Unixes / MacOS X / Windows.

Author(s)
Nikon Systems Inc.

2005-1-12

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
