########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library rmetasim
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.0.1
%define packrel  0
%define rel      1
%define packname rmetasim
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: GPL
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - An individual-based population genetic simulation environment
BuildRequires: R-base
PreReq: R-base
Requires:  R-ape
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
An interface between R and the metasim simulation engine.
Facilitates the use of the metasim engine to build and run
individual based population genetics simulations. The
simulation environment is documented in: Allan
Strand. Metasim 1.0: an individual-based environment
for simulating population genetics of complex population
dynamics. Mol. Ecol. Notes, 2:373-376, 2002. (Please
contact Allan Strand with comments, bug reports, etc).

Author(s)
Allan Strand <stranda@cofc.edu>,
James Niehaus

2004-9-20

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
