########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library ROCR
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.0
%define packrel  1
%define rel      1
%define packname ROCR
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL (version 2 or later)
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Visualizing the performance of scoring classifiers.
BuildRequires: R-base
PreReq: R-base
Requires:  R-gplots
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
ROC graphs, sensitivity/specificity curves, lift charts,
and precision/recall plots are popular examples of trade-off
visualizations for specific pairs of performance measures. ROCR is a
flexible tool for creating cutoff-parametrized 2D performance curves
by freely combining two from over 25 performance measures (new
performance measures can be added using a standard interface).
Curves from different cross-validation or bootstrapping runs can be
averaged by different methods, and standard deviations, standard
errors or box plots can be used to visualize the variability across
the runs. The parametrization can be visualized by printing cutoff
values at the corresponding curve positions, or by coloring the
curve according to cutoff. All components of a performance plot can
be quickly adjusted using a flexible parameter dispatching
mechanism. Despite its flexibility, ROCR is easy to use, with only
three commands and reasonable default values for all optional
parameters.

Author(s)
Tobias Sing, Oliver Sander, Niko Beerenwinkel, Thomas Lengauer

2005-02-23

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --html
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --html
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
