########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library RQuantLib
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      0.1.10
%define packrel  0
%define rel      1
%define packname RQuantLib
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: GPL Version 2 or later for RQuantLib; QuantLib itself is releasedunder an Open Source license as well
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - R interface to the QuantLib libraries
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
The RQuantLib packages provides access to (some) of the QuantLib
functions from within R. It is currently limited to some Option
pricing and analysis functions.
The QuantLib project aims to provide a comprehensive software
framework for quantitative finance. The goal is to provide a
standard free/open source library to quantitative analysts and
developers for modeling, trading, and risk management of financial
assets.
You need to have QuantLib and Boost installed in order to use RQuantLib.

Author(s)
Dirk Eddelbuettel <edd@debian.org> for the R interface, the QuantLib
group for QuantLib (http://www.quantlib.org/html/group.html)

$Date: 2004/09/12 19:01:38 $

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
