########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library SciViews
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      0.8
%define packrel  8
%define rel      1
%define packname SciViews
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL 2 or above
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - 
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package bundle:
SciViews GUI API
A series of packages to implement a complete reusable GUI API for R.

Author(s)
Philippe Grosjean & Eric Lecoutre

2005-08-18

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/svMisc/src && (cd %{packname}/svMisc/src; rm -f *.o *.so)
test -d %{packname}/svIO/src && (cd %{packname}/svIO/src; rm -f *.o *.so)
test -d %{packname}/svViews/src && (cd %{packname}/svViews/src; rm -f *.o *.so)
test -d %{packname}/svDialogs/src && (cd %{packname}/svDialogs/src; rm -f *.o *.so)
test -d %{packname}/svSocket/src && (cd %{packname}/svSocket/src; rm -f *.o *.so)
test -d %{packname}/svGUI/src && (cd %{packname}/svGUI/src; rm -f *.o *.so)
test -d %{packname}/svIDE/src && (cd %{packname}/svIDE/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/svMisc
%{prefix}/lib/R/library/svIO
%{prefix}/lib/R/library/svViews
%{prefix}/lib/R/library/svDialogs
%{prefix}/lib/R/library/svSocket
%{prefix}/lib/R/library/svGUI
%{prefix}/lib/R/library/svIDE


####### end of spec-file ################################################
