########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library spdep
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      0.3
%define packrel  12
%define rel      1
%define packname spdep
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL version 2 or newer
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Spatial dependence: weighting schemes, statistics and models
BuildRequires: R-base
PreReq: R-base
Requires:  R-maptools R-tripack R-SparseM
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
A collection of functions to create spatial weights matrix
objects from polygon contiguities, from point patterns by distance and
tesselations, for summarising these objects, and for permitting their
use in spatial data analysis; a collection of tests for spatial
autocorrelation, including global Moran's I, Geary's C, Hubert/Mantel
general cross product statistic, Empirical Bayes estimates and Assunção/Reis
Index, Getis/Ord G and multicoloured join count statistics,
local Moran's I and Getis/Ord G, saddlepoint approximations for global
and local Moran's I; and functions for estimating spatial simultaneous
autoregressive (SAR) models.

Author(s)
Roger Bivand <Roger.Bivand@nhh.no>, with contributions by Luc Anselin,
Andrew Bernat, Marilia Carvalho, Stéphane Dray, Rein Halbersma,
Nicholas Lewin-Koh, Hisaji Ono, Michael Tiefelsdorf, and Danlin Yu.

2005-04-19

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
