########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library strucchange
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.2
%define packrel  11
%define rel      1
%define packname strucchange
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Testing for Structural Change
BuildRequires: R-base
PreReq: R-base
Requires:  R-zoo R-sandwich
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
Testing, dating and monitoring of structural change in
linear regression relationships.
strucchange features tests/methods from the generalized
fluctuation test framework as well as from the F test (Chow
test) framework. This includes methods to fit, plot and test
fluctuation processes (e.g., CUSUM, MOSUM, recursive/moving
estimates) and F statistics, respectively.
It is possible to monitor incoming data online using
fluctuation processes.
Finally, the breakpoints in regression models with structural
changes can be estimated together with confidence intervals.
Emphasis is always given to methods for visualizing the data.

Author(s)
Achim Zeileis, Friedrich Leisch, Bruce Hansen,
Kurt Hornik, Christian Kleiber, Andrea Peters

2005-09-07

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
