########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library systemfit
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      0.7
%define packrel  2
%define rel      1
%define packname systemfit
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL version 2 or newer
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Simultaneous Equation Estimation Package
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
This package contains functions for fitting simultaneous
systems of linear and nonlinear equations using Ordinary Least
Squares (OLS), Weighted Least Squares (WLS), Seemingly Unrelated
Regressions (SUR), Two-Stage Least Squares (2SLS), Weighted
Two-Stage Least Squares (W2SLS), Three-Stage Least Squares (3SLS),
and Weighted Three-Stage Least Squares (W3SLS).

Author(s)
Jeff D. Hamann <jeff.hamann@forestinformatics.com> and
Arne Henningsen <ahenningsen@agric-econ.uni-kiel.de>

2004/08/19

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
