########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library udunits
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.2
%define packrel  0
%define rel      1
%define packname udunits
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}.tar.gz
Copyright: GPL version 2 or newer
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - interface to Unidata's routines to convert units
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
This package provides an R interface to the Unidata
udunits library routines, which can convert quantities between various units.
Units are indicated by human-readable strings, such as "m/s", "J",
"kg", or "in".  Routines for converting any quantity in known units
to other compatible units are provided.  Of particular use are the
time and calendar conversion routines.  Calendar dates are given
with units such as "days since 1900-01-01", for example.  Values with
this unit can be converted to normal, readable calendar dates.  This
will let you find that "32018 days since 1900-01-01" is actually
31 Aug 1987.  These routines follow the library's C interface, so consult that
section of Unidata's udunits manual for reference.  Here are some
example formatted units strings that can be used: "10 kilogram.meters/seconds2",
"10 kg-m/sec2", "10 kg m/s^2", "(PI radian)2", "degF", "degC", "100rpm",
"geopotential meters", "33 feet water".  Note that the udunits library
must already be installed on your machine for this package to work.

Author(s)
David Pierce



%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
