########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library varSelRF
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      0.6
%define packrel  2
%define rel      1
%define packname varSelRF
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL version 2 or newer
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Variable selection using random forests
BuildRequires: R-base
PreReq: R-base
Requires:  R-randomForest
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
Variable selection from random forests
using both backwards variable elimination (for the selection of
small sets of non-redundant variables) and selection based on the
importance spectrum (somewhat similar to scree plots; for the
selection of large, potentially highly-correlated variables).
Main applications in high-dimensional data
(e.g., microarray data, and other genomics and proteomics
applications).

Author(s)
Ramon Diaz-Uriarte <rdiaz@ligarto.org>

2005-07-27

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
