# based on a spec file generated by build-R-contrib-rpms.pl #################
# spec file for R view economics
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      1.0
%define packrel  2.1.1
%define rel      1.vrdc
%define viewname view-core-bayesian-econ
%define prefix   /usr
%define library  %{prefix}/lib/R/library

Name: R-%{viewname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: %{name}_%{ver}.tgz
Copyright: LGPL
URL: http://cran.r-project.org/src/contrib/Views/index.html
Group: Applications/Math
Summary: R  %{viewname} - Core/joint files for views "Bayesian" and "Econometrics"
BuildRequires: R-base
PreReq: R-base 
BuildRoot: /var/tmp/%{viewname}-buildroot

%description
R %{viewname}: Provides base files for R  views "Bayesian" and "Econometrics". See those packages for further details.

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build


%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT%{library}
#install -p -d -D *  $RPM_BUILD_ROOT%{library}
mv *  $RPM_BUILD_ROOT%{library}/
chmod -R a+rX  $RPM_BUILD_ROOT%{library}
chown -R root.root  $RPM_BUILD_ROOT%{library}
# create DESCRIPTION
wget %{url}

%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{library}/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{library}/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc index.html
%{library}/bayesm
%{library}/coda
%{library}/Hmisc
%{library}/lme4
%{library}/MNP


####### end of spec-file ################################################
