# based on a spec file generated by build-R-contrib-rpms.pl #################
# spec file for R view econometrics
#
# Lars Vilhuber (lars.vilhuber@cornell.edu)
#
%define ver      1.0
%define packrel  2.1.1
%define rel      1.vrdc
%define viewname view-econometrics
%define prefix   /usr
%define library  %{prefix}/lib/R/library

Name: R-%{viewname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: %{name}_%{ver}.tgz
Copyright: LGPL
URL: http://cran.r-project.org/src/contrib/Views/Econometrics.html
Group: Applications/Math
Summary: R view %{viewname} - Computational Econometrics
BuildRequires: R-base
PreReq: R-base R-view-core-bayesian-econ
BuildRoot: /var/tmp/%{viewname}-buildroot

%description
R %{viewname}:
Maintainer: Achim Zeileis

Base R ships with a lot of functionality useful for computational econometrics, in particular in the stats package. This functionality is complemented by many packages on CRAN, a brief overview is given below. There is also a considerable overlap between the tools for econometrics in this view and finance in the Finance view. Furthermore, the finance SIG is a suitable mailing list for obtaining help and discussing questions about both computational finance and econometrics. The packages in this view can be roughly structured into the following topics. If you think that some package is missing from the list, please let me know.

    * Linear regression models : Linear models can be fitted (via OLS) with lm() (from stats) and standard tests for model comparisons are available in various methods such as summary() and anova() . Analogous functions that also support asymptotic tests ( z instead of t tests, and Chi-squared instead of F tests) and plug-in of other covariance matrices are coeftest() and waldtest() in lmtest. Tests of more general linear hypotheses are implemented in linear.hypothesis() in car. HC and HAC covariance matrices that can be plugged into these functions are available in sandwich. The packages car and lmtest also provide a large collection of further methods for diagnost checking in linear regression models.
    * Microeconometrics : Many standard microeconometric models belong to the family of generalized linear models (GLM) and can be fitted by glm() from package stats. This includes in particular logit and probit models for modelling choice data and poisson models for count data. Negative binomial GLMs are available via glm.nb() in package MASS from the VR bundle. Zero-inflated count models are provided in zicounts. Further over-dispersed and inflated models, including hurdle models, are available in package pscl. Bivariate poisson regression models are implemented in bivpois. Basic censored regression models (e.g., tobit models) can be fitted by survreg() in survival. Further more refined tools for microecnometrics are provided in micEcon. The package bayesm implements a Bayesian approach to microeconometrics and marketing. Inference for relative distributions is contained in package reldist.
    * Further regression models : Various extensions of the linear regression model and other model fitting techniques are available in base R and several CRAN packages. Nonlinear least squares modelling is availble in nls() in package stats. Relevant packages include quantreg (quantile regression), sem (linear structural equation models, including two-stage least squares), systemfit (simultaneous equation estimation), betareg (beta regression), nlme (nonlinear mixed-effect models), VR (multinomial logit models in package nnet) and MNP (Bayesian multinomial probit models). The packages Design and Hmisc provide several tools for extended handling of (generalized) linear regression models.
    * Basic time series infrastructure : The class "ts" in package stats is R's standard class for regularly spaced time series which can be coerced back and forth without loss of information to "zooreg" from package zoo. zoo provides infrastructure for both regularly and irregularly spaced time series (the latter via the class "zoo" ) where the time information can be of arbitrary class. Several other implementations of irregular time series building on the "POSIXt" time-date classes are available in its, tseries and fCalendar which are all aimed particularly at finance applications (see the Finance view).
    * Time series modelling : Classical time series modelling tools are contained in the stats package and include arima() for ARIMA modelling and Box-Jenkins-type analysis. Furthermore stats provides StructTS() for fitting structural time series and decompose() and HoltWinters() for time series filtering and decomposition. A convenient interface for fitting dynamic regression models via OLS is available in dynlm; a different approach that also works with other regression functions is implemented in dyn. More advanced dynamic system equations can be fitted using dse. Unit root and cointegration techniques are available in urca, uroot and tseries.
    * Matrix manipulations : As a vector- and matrix-based language, base R ships with many powerful tools for doing matrix manipulations, which are complemented by the packages Matrix and SparseM.
    * Inequality : For measuring inequality, concentration and poverty the package ineq provides some basic tools such as Lorenz curves, Pen's parade, the Gini coefficient and many more.
    * Structural change : R is particularly strong when dealing with structural changes and changepoints in parametric models, see strucchange and segmented.
    * Data sets : Many of the packages in this view contain collections of data sets from the econometric literature and the package Ecdat contains a complete collection of data sets from various standard econometric textbooks. Package pwt provides the Penn world table.

#%define _unpackaged_files_terminate_build 0
#%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build


%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT%{library}
#install -p -d -D *  $RPM_BUILD_ROOT%{library}
mv *  $RPM_BUILD_ROOT%{library}/
chmod -R a+rX  $RPM_BUILD_ROOT%{library}
chown -R root.root  $RPM_BUILD_ROOT%{library}
# create DESCRIPTION
wget %{url}

%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{library}/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{library}/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc Econometrics.html
%{library}/acepack
%{library}/akima
%{library}/betareg
%{library}/bivpois
%{library}/car
%{library}/chron
%{library}/DAAG
%{library}/Design
%{library}/dse1
%{library}/dse2
%{library}/dyn
%{library}/dynlm
%{library}/e1071
%{library}/Ecdat
%{library}/fBasics
%{library}/fCalendar
%{library}/ineq
%{library}/its
%{library}/leaps
%{library}/lmtest
%{library}/Matrix
%{library}/micEcon
%{library}/mlbench
%{library}/mlmRev
%{library}/mvtnorm
%{library}/oz
%{library}/pscl
%{library}/pwt
%{library}/quadprog
%{library}/quantreg
%{library}/randomForest
%{library}/reldist
%{library}/rgl
%{library}/sandwich
%{library}/scatterplot3d
%{library}/segmented
%{library}/sem
%{library}/setRNG
%{library}/SparseM
%{library}/strucchange
%{library}/systemfit
%{library}/tframe
%{library}/tripack
%{library}/tseries
%{library}/urca
%{library}/uroot
%{library}/xtable
%{library}/zicounts
%{library}/zoo


####### end of spec-file ################################################
