########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library VR
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      7.2
%define packrel  8
%define rel      1
%define packname VR
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL (version 2 or later)  See file LICENCE.
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - 
BuildRequires: R-base
PreReq: R-base
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package bundle:
Functions and datasets to support Venables and
Ripley, 'Modern Applied Statistics with S' (4th edition).

Author(s)
S original by Venables & Ripley.
R port by Brian Ripley <ripley@stats.ox.ac.uk>, following earlier
work by Kurt Hornik and Albrecht Gebhardt.

2004-09-09

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/MASS/src && (cd %{packname}/MASS/src; rm -f *.o *.so)
test -d %{packname}/class/src && (cd %{packname}/class/src; rm -f *.o *.so)
test -d %{packname}/nnet/src && (cd %{packname}/nnet/src; rm -f *.o *.so)
test -d %{packname}/spatial/src && (cd %{packname}/spatial/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/MASS
%{prefix}/lib/R/library/class
%{prefix}/lib/R/library/nnet
%{prefix}/lib/R/library/spatial


####### end of spec-file ################################################
