########## automatically generated by build-R-contrib-rpms.pl #################
# spec file for R library Zelig
#
# D. Steuer <detlef.steuer@gmx.de>
#
%define ver      2.4
%define packrel  1
%define rel      1
%define packname Zelig
%define prefix   /usr

Name: R-%{packname}
Version: %{ver}.R%{packrel}
Release: %{rel}
Source: ftp://cran.r-project.org/pub/R/contrib/main/%{packname}_%{ver}-%{packrel}.tar.gz
Copyright: GPL version 2 or newer
URL: http://cran.r-project.org/contrib
Group: Applications/Math
Summary: R package %{packname} - Zelig: Everyone's Statistical Software
BuildRequires: R-base
PreReq: R-base
Requires: 
BuildRoot: /var/tmp/%{packname}-buildroot

%description
R package:
Zelig is an easy-to-use program that can estimate, and
help interpret the results of, an enormous range of
statistical models. It literally is ``everyone's statistical
software'' because Zelig's simple unified framework
incorporates everyone else's (R) code. We also hope it will
become ``everyone's statistical software'' for applications
and teaching, and so have designed Zelig so that anyone can
easily use it or add their programs to it.  Zelig also comes
with infrastructure that facilitates the use of any existing
method, such as by allowing multiply imputed data for any
model, and mimicking the program Clarify (for Stata) that
takes the raw output of existing statistical procedures and
translates them into quantities of direct interest.

Author(s)
Kosuke Imai <kimai@Princeton.Edu>,
Gary King <king@harvard.edu>,
Olivia Lau <olau@fas.harvard.edu>

2005-08-15

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0

%prep
%setup -T -c -a 0

%build
cp %{packname}/DESCRIPTION .

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT%{prefix}/lib/R/library
%{prefix}/bin/R CMD INSTALL -l $RPM_BUILD_ROOT%{prefix}/lib/R/library %{packname}
%{prefix}/bin/R CMD check %{packname}
test -d %{packname}/src && (cd %{packname}/src; rm -f *.o *.so)


%clean
rm -rf $RPM_BUILD_ROOT

%post
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%postun
%{prefix}/bin/R CMD perl %{prefix}/lib/R/share/perl/build-help.pl --htmllists
cat %{prefix}/lib/R/library/*/CONTENTS > %{prefix}/lib/R/doc/html/search/index.txt

%files
%doc DESCRIPTION
%{prefix}/lib/R/library/%{packname}


####### end of spec-file ################################################
